#!/bin/bash

# Install fzf
# https://github.com/junegunn/fzf
function install_fzf {
    # Check if git is installed
    check_package "git" install_fzf

    NAME='fzf'

    # Install
    echo_message info "Installing $NAME..."
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install

    # Done
    echo_message success "Installation of $NAME complete."
    whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 56
    thirdparty
}