#!/bin/bash

# Oh My Fish(omf) fish shell framework with theme "bobthefish"
# https://github.com/oh-my-fish/oh-my-fish
function install_omf {
	# Check if fish shell(fish) is installed
	check_package "fish" install_omf

    NAME='Oh My Fish with theme "bobthefish"'

    # Download and install Oh My Fish
    if [ ! -f ~/.local/share/omf ]; then
        echo_message info "$NAME is not installed."
		echo 'Proceeding'

        # Install
		echo_message info "Installing $NAME..."
		curl -L https://get.oh-my.fish | fish

        # Install bobthefish theme
        echo 'omf install bobthefish' | fish

        # Done
		echo_message success "Installation of $NAME complete."
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 56
		thirdparty
    else
        # Install bobthefish theme
        echo 'omf install bobthefish' | fish

        # Already installed
		echo_message info "$NAME already installed."
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 56
		thirdparty
    fi
}